# This is a basic workflow to help you get started with Actions

name: REFERENCIAS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
jobs:
  contexto-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Info de ejecución
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Repo: ${{ github.repository }}"
          echo "Rama: ${{ github.ref }}"
          echo "Evento: ${{ github.event_name }}"
          echo "Sistema operativo: ${{ runner.os }}"
      - name: Dump GitHub context
        run: echo "${{ toJson(github) }}"
